CREATE TABLE IF NOT EXISTS Actors (
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    Nameid  integer NOT NULL,
    Nationid integer NOT NULL,
	Number     integer NOT NULL,
	Honorar float NOT NULL
);

CREATE TABLE IF NOT EXISTS Nations (
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    Name   varchar(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS Names (
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    Family  varchar(30) NOT NULL,
    Given   varchar(30) NOT NULL
);

-- ALTER TABLE Actors ADD CONSTRAINT Nations FOREIGN KEY (Nationid) REFERENCES Nations (id);
-- ALTER TABLE Actors ADD CONSTRAINT Names FOREIGN KEY (Nameid) REFERENCES Names (id);

ALTER TABLE "actors" ADD CONSTRAINT "actors_fk1" FOREIGN KEY ("nameid") REFERENCES "names"("id");
ALTER TABLE "actors" ADD CONSTRAINT "actors_fk2" FOREIGN KEY ("nationid") REFERENCES "nations"("id");